project:
  type: website
  output-dir: docs

website:
  title: "Steven Abrams"
  repo-url: https://github.com/stevenabramslucp2479/stevenabramslucp2479.github.io
  twitter-card:
    creator: "@stevenabramslucp2479"
    card-style: summary_large_image
    image: ""
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - about.md
      - projects.md

format:
  html:
    theme:
      light: minty
      dark: slate
    css: styles.css
    toc: true

editor: visual

