project:
  type: website
  output-dir: docs

website:
  title: "Steven Abrams"
  repo-url: https://github.com/stevenabramslucp2479/stevenabramslucp2479.github.io
  twitter-card:
    creator: "@stevenabramslucp2479"
    card-style: summary_large_image
    image: ""
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - about.qmd
      - research.qmd
      - publications.qmd
      - cv.qmd
      - text: Resources
        menu:
          - text: "Tutorials"
            href: tutorials.qmd
          - text: "---"  # separator line
          - text: "Presentations"
            href: presentations.qmd
          - text: "---"  # separator line
          - text: "Software"
            href: software.qmd

format:
  html:
    theme:
      light: minty
      dark: slate
    css: styles.css
    toc: true

editor: visual

